version: '3.7'

networks:
  default:
    name: llama_net
    external: true

services:
  llama-server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    command: python3 server.py