version: '3.7'

services:
  embedding-server:
    env_file:
      - .env
    build: .
    container_name: embedding-server
    environment:
      - PYTHONUNBUFFERED=True
    restart: always
    ports:
      - '8889:8889'
    command: python3 server.py