version: '3.7'

networks:
  default:
    name: embedding_net
    external: true

services:
  embedding-server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8889:8889'
    command: python3 server.py